### ISSUE TITLE
manager clashed log

### ISSUE THREAD

**Issue by greenredstone** [LSPosed/LSPosed#171] opened 2021-02-23 00:46 UTC
Build version: v1.0.0 (5309) 
Current date: 2021-02-23 08:43:47 
Device: Xiaomi Redmi K20 Pro 
 
SDK: 30 
 
Stack trace:  
c.e.b.v: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at c.e.b.i.b(:13)
	at d.a.a.b.f.d$a.d(:5)
	at i.l0.f.e$a.run(:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at c.e.b.c0.a.o(:6)
	at c.e.b.a0.z.a.a(:4)
	at c.e.b.i.b(:8)
	... 5 more

**Comment by yujincheng08** [comment] 2021-02-23 00:46
duplicate of #169

**Closed by yujincheng08** 2021-02-23 00:46 UTC
