### ISSUE TITLE
[Bug] LSP1.91Xposed Module not displayed

### ISSUE THREAD

**Issue by danshenlian** [LSPosed/LSPosed#2760] opened 2023-09-17 01:02 UTC
### Steps to reproduce/复现步骤

![Screenshot_2023-09-17-08-42-06-55_084ab3bc34f7aa7ccff83653f52abafc](https://github.com/LSPosed/LSPosed/assets/38625092/a5b2cede-df32-493b-bfac-b6ebcb7e2872)
![Screenshot_2023-09-14-20-16-55-45_084ab3bc34f7aa7ccff83653f52abafc](https://github.com/LSPosed/LSPosed/assets/38625092/b07d6a5c-db9e-4003-800d-635d6c8e0663)

### Expected behaviour/预期行为

在Lsp显示已经安装的插件模块，然后启用作用域

### Actual behaviour/实际行为

xposed模块页空白，安装了xposed插件，不能启用。

### Xposed Module List/Xposed 模块列表

```shell
微X
```

### Magisk Module List/Magisk 模块列表

```shell
shamiko
zygisk-lspoesd
uperf
```

### LSPosed version/LSPosed 版本

1.9.1

### Android version/Android 版本

Android13

### Magisk version/Magisk 版本

magisk25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-09-17T08_54_34.625524.zip](https://github.com/LSPosed/LSPosed/files/12641826/LSPosed_2023-09-17T08_54_34.625524.zip)

**Comment by yujincheng08** [comment] 2023-09-17 03:07
Duplicate of #2638

**Closed by yujincheng08** 2023-09-17 03:07 UTC
Labels: bug
