### ISSUE TITLE
[Bug] [14Beta2.1] Not hooking to Telecom package during boot

### ISSUE THREAD

**Issue by siavash79** [LSPosed/LSPosed#2553] opened 2023-06-06 13:19 UTC
### Steps to reproduce/复现步骤

1. Write hooks for package com.android.server.telecom
2. Reboot device
3. Lsposed doesn't hook to telecom server
4. Restart zygote - kill $(pidof zygote64)
5. Lsposed successfully hooks to telecom server

### Expected behaviour/预期行为

It's expected that Lsposed hooks to telecom server at boot - Note: the issue was not present on previous Android versions

### Actual behaviour/实际行为

Lsposed can't hook to telecom server at boot. It does if zygote is restarted

### Xposed Module List/Xposed 模块列表

```shell
sh.siava.AOSPMods (https://github.com/siavash79/AOSPMods) (https://github.com/siavash79/AOSPMods/blob/canary/app/src/main/java/sh/siava/AOSPMods/modpacks/telecom/CallVibrator.java)
```

### Magisk Module List/Magisk 模块列表

```shell
modules\zygisk-sui
modules\zygisk_shamiko
modules\zygisk_lsposed
modules\wireguard
modules\volte4pixel4
modules\safetynet-fix
modules\Pixel5VolteVoWiFi
modules\Pixel5_N.U
modules\AOSPMods
```

### LSPosed version/LSPosed 版本

6901

### Android version/Android 版本

14 Beta 2.1 - UPB2.230407.019

### Magisk version/Magisk 版本

26100

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-06-06T16_39_44.740232.zip](https://github.com/LSPosed/LSPosed/files/11665046/LSPosed_2023-06-06T16_39_44.740232.zip)
![photo_2023-06-06_16-45-35](https://github.com/LSPosed/LSPosed/assets/25217714/f0eb05cd-d7bc-454c-8133-b163cdac964b)

**Comment by yujincheng08** [comment] 2023-06-07 16:46
here's the scope list from lsposed's log:
```
com.android.systemui:tuner/10219
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPEntry
com.android.systemui:fgservices/10219
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPEntry
com.android.phone/1001
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPEntry
com.android.systemui:screenshot/10219
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPEntry
sh.siava.AOSPMods/1110476
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPEntry
com.google.android.apps.nexuslauncher/10201
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPEntry
sh.siava.AOSPMods/1210476
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPEntry
com.android.systemui:appclips.screenshot/10219
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPEntry
sh.siava.AOSPMods/1010476
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPEntry
com.android.settings/1000
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPEntry
sh.siava.AOSPMods/10476
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPEntry
com.android.systemui:sweetsweetdesserts/10219
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPEntry
com.android.systemui/10219
	sh.siava.AOSPMods
		sh.siava.AOSPMods.XPEntry
```

what do you mean by `com.android.server.telecom`? Do you mean `System Framework`'s not hooking the first boot?

**Comment by yujincheng08** [comment] 2023-06-07 17:01
From the log of the first boot, I saw:

```
[ 2023-06-06T16:35:09.364     1000:  1801:  1801 I/LSPosed         ] Loading xposed for android/1000
[ 2023-06-06T16:35:10.442     1000:  1801:  1801 I/LSPosed-Bridge  ] Loading legacy module sh.siava.AOSPMods from /data/app/~~aLcE4xRCzFy7muS8nljGEw==/sh.siava.AOSPMods-eCUpcPa_Skc7c_17qX75ww==/base.apk
[ 2023-06-06T16:35:10.493     1000:  1801:  1801 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPEntry
[ 2023-06-06T16:35:16.372    10219:  2352:  2352 I/LSPosed         ] Loading xposed for com.android.systemui/10219
[ 2023-06-06T16:35:16.376    10219:  2352:  2352 I/LSPosed-Bridge  ] Loading legacy module sh.siava.AOSPMods from /data/app/~~aLcE4xRCzFy7muS8nljGEw==/sh.siava.AOSPMods-eCUpcPa_Skc7c_17qX75ww==/base.apk
[ 2023-06-06T16:35:16.498    10219:  2352:  2352 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPEntry
[ 2023-06-06T16:35:17.430     1001:  2626:  2626 I/LSPosed         ] Loading xposed for com.android.phone/1001
[ 2023-06-06T16:35:17.436     1001:  2626:  2626 I/LSPosed-Bridge  ] Loading legacy module sh.siava.AOSPMods from /data/app/~~aLcE4xRCzFy7muS8nljGEw==/sh.siava.AOSPMods-eCUpcPa_Skc7c_17qX75ww==/base.apk
[ 2023-06-06T16:35:17.507     1001:  2626:  2626 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPEntry
[ 2023-06-06T16:35:17.526     1000:  2643:  2643 I/LSPosed         ] Loading xposed for com.android.settings/1000
[ 2023-06-06T16:35:17.543     1000:  2643:  2643 I/LSPosed-Bridge  ] Loading legacy module sh.siava.AOSPMods from /data/app/~~aLcE4xRCzFy7muS8nljGEw==/sh.siava.AOSPMods-eCUpcPa_Skc7c_17qX75ww==/base.apk
[ 2023-06-06T16:35:17.629     1000:  2643:  2643 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPEntry
[ 2023-06-06T16:35:19.648    10201:  3279:  3279 I/LSPosed         ] Loading xposed for com.google.android.apps.nexuslauncher/10201
[ 2023-06-06T16:35:19.655    10201:  3279:  3279 I/LSPosed-Bridge  ] Loading legacy module sh.siava.AOSPMods from /data/app/~~aLcE4xRCzFy7muS8nljGEw==/sh.siava.AOSPMods-eCUpcPa_Skc7c_17qX75ww==/base.apk
[ 2023-06-06T16:35:19.722    10201:  3279:  3279 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPEntry

```

Looks like all apps in the scope are loading your module.

**Comment by yujincheng08** [comment] 2023-06-07 17:12
Further from the log, I saw this:

The first boot:
```
[ 2023-06-06T16:35:10.442     1000:  1801:  1801 I/LSPosed-Bridge  ] Loading legacy module sh.siava.AOSPMods from /data/app/~~aLcE4xRCzFy7muS8nljGEw==/sh.siava.AOSPMods-eCUpcPa_Skc7c_17qX75ww==/base.apk
[ 2023-06-06T16:35:10.493     1000:  1801:  1801 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPEntry
[ 2023-06-06T16:35:17.338     1000:  1801:  1801 D/LSPosed         ] LoadedApk#getClassLoader starts: pkg=android, prc=android
[ 2023-06-06T16:35:17.338     1000:  1801:  1801 D/LSPosed         ] LoadedApk#getClassLoader ends: /system/priv-app/Telecom/Telecom.apk -> dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/Telecom/Telecom.apk"],nativeLibraryDirectories=[/system/priv-app/Telecom/lib/arm64, /system/lib64, /system_ext/lib64, /system/lib64, /system_ext/lib64]]]: pkg=android, prc=android
[ 2023-06-06T16:35:17.338     1000:  1801:  1801 D/LSPosed         ] Call handleLoadedPackage: packageName=com.android.server.telecom processName=android isFirstPackage=false classLoader=dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/Telecom/Telecom.apk"],nativeLibraryDirectories=[/system/priv-app/Telecom/lib/arm64, /system/lib64, /system_ext/lib64, /system/lib64, /system_ext/lib64]]] appInfo=ApplicationInfo{49e78ed com.android.server.telecom}: pkg=android, prc=android
```

The second boot:
```
[ 2023-06-06T16:38:02.957     1000: 22665: 22665 I/LSPosed-Bridge  ] Loading legacy module sh.siava.AOSPMods from /data/app/~~aLcE4xRCzFy7muS8nljGEw==/sh.siava.AOSPMods-eCUpcPa_Skc7c_17qX75ww==/base.apk
[ 2023-06-06T16:38:03.088     1000: 22665: 22665 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPEntry
[ 2023-06-06T16:38:14.988     1000: 22665: 22665 D/LSPosed         ] LoadedApk#getClassLoader starts: pkg=android, prc=android
[ 2023-06-06T16:38:14.989     1000: 22665: 22665 D/LSPosed         ] LoadedApk#getClassLoader ends: /system/priv-app/Telecom/Telecom.apk -> dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/Telecom/Telecom.apk"],nativeLibraryDirectories=[/system/priv-app/Telecom/lib/arm64, /system/lib64, /system_ext/lib64, /system/lib64, /system_ext/lib64]]]: pkg=android, prc=android
[ 2023-06-06T16:38:14.989     1000: 22665: 22665 D/LSPosed         ] Call handleLoadedPackage: packageName=com.android.server.telecom processName=android isFirstPackage=false classLoader=dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/Telecom/Telecom.apk"],nativeLibraryDirectories=[/system/priv-app/Telecom/lib/arm64, /system/lib64, /system_ext/lib64, /system/lib64, /system_ext/lib64]]] appInfo=ApplicationInfo{8d28761 com.android.server.telecom}: pkg=android, prc=android
[ 2023-06-06T16:38:15.009     1000: 22665: 22665 I/LSPosed-Bridge  ] AOSPMods Version: canary-253
```

LSPosed prints log that loads your module and `Call handleLoadedPackage: packageName=com.android.server.telecom` on both boots, but only on the second boot your module prints log. Please confirm whether it is truly LSPosed's issue.

**Comment by yujincheng08** [comment] 2023-06-07 17:24
Once `Loading class` logs are printed without `Failed to load class` logs

https://github.com/LSPosed/LSPosed/blob/8ebdfc72f95dc03e8ea4ef24451af7962df0d29e/core/src/main/java/de/robv/android/xposed/XposedInit.java#L260-L293

your module entry must be added into `sLoadedPackageCallbacks` by `XposedBridge.hookLoadPackage`:

https://github.com/LSPosed/LSPosed/blob/8ebdfc72f95dc03e8ea4ef24451af7962df0d29e/core/src/main/java/de/robv/android/xposed/XposedBridge.java#L288-L292


Note that entries of `sLoadedPackageCallbacks` won't be removed. So when `Call handleLoadedPackage` logs are printed without `error when hooking LoadedApk#getClassLoader` logs, entries of `sLoadedPackageCallbacks` must be called by `callAll` with an `XC_LoadPackage.LoadPackageParam` created with `sLoadedPackageCallbacks`

https://github.com/LSPosed/LSPosed/blob/8ebdfc72f95dc03e8ea4ef24451af7962df0d29e/core/src/main/java/org/lsposed/lspd/hooker/LoadedApkGetCLHooker.java#L110-L123

https://github.com/LSPosed/LSPosed/blob/8ebdfc72f95dc03e8ea4ef24451af7962df0d29e/core/src/main/java/org/lsposed/lspd/hooker/LoadedApkGetCLHooker.java#L159-L161

**Comment by siavash79** [comment] 2023-06-08 01:21
Thanks!

I'll study all your comments in 2-3 days from my PC.

But for the time being this is the situation: between first and second zygote load, in which as you can see there's very short duration, no elements change at all: no app update, no lsposed config change etc.

So it seems like there's a difference in lsposed behavior between these two situations.

**Comment by siavash79** [comment] 2023-06-08 01:33
> where it behaves differently? i hv show u the code where ur module is loaded and called. that's all i can do from the info u provided. could u show me where your module is not loaded or called?

Well apart from what logs may contain, I noticed that the hooks (I tested explicitly the one I linked in first post) do not work at all in the first load (phone state change is supposed to cause vibration, but it doesn't. But once zygote is restarted, the hooks that are responsible for vibration start working normally)

**Comment by yujincheng08** [comment] 2023-06-08 01:35
but i saw internal heooks of lsposed's work from the log?

**Comment by siavash79** [comment] 2023-06-08 01:39
Let me modify the code and add log entries on handle load package and hooked methods so that we can study this further.

I'll revert in 2 3 days

**Comment by yujincheng08** [comment] 2023-06-08 08:16
Further looking at your log, I found the first boot your module had printed log that confirms it was loaded:

```
[ 2023-06-06T16:35:17.338     1000:  1801:  1801 D/LSPosed         ] LoadedApk#getClassLoader starts: pkg=android, prc=android
[ 2023-06-06T16:35:17.338     1000:  1801:  1801 D/LSPosed         ] LoadedApk#getClassLoader ends: /system/priv-app/Telecom/Telecom.apk -> dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/Telecom/Telecom.apk"],nativeLibraryDirectories=[/system/priv-app/Telecom/lib/arm64, /system/lib64, /system_ext/lib64, /system/lib64, /system_ext/lib64]]]: pkg=android, prc=android
[ 2023-06-06T16:35:17.338     1000:  1801:  1801 D/LSPosed         ] Call handleLoadedPackage: packageName=com.android.server.telecom processName=android isFirstPackage=false classLoader=dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/Telecom/Telecom.apk"],nativeLibraryDirectories=[/system/priv-app/Telecom/lib/arm64, /system/lib64, /system_ext/lib64, /system/lib64, /system_ext/lib64]]] appInfo=ApplicationInfo{49e78ed com.android.server.telecom}: pkg=android, prc=android
[ 2023-06-06T16:35:17.656     1000:  1801:  1801 I/LSPosed-Bridge  ] AOSPMods Version: canary-253
[ 2023-06-06T16:35:17.676     1000:  1801:  1801 I/LSPosed-Bridge  ] AOSPMods Records: 197
```

and its dong hooks, for example:

```
[ 2023-06-06T16:35:17.759     1000:  1801:  1801 V/LSPlant         ] lsplant.cc:511#bool lsplant::(anonymous namespace)::DoHook(lsplant::art::ArtMethod *, lsplant::art::ArtMethod *, lsplant::art::ArtMethod *): Hooking: target = void com.android.server.telecom.InCallController.onCallStateChanged(com.android.server.telecom.Call, int, int)(0x7b4f6fcbf8), hook = void LSPHooker_.onCallStateChanged(java.lang.Object, java.lang.Object, int, int)(0x7b4ea58040), backup = void LSPHooker_.backup(java.lang.Object, java.lang.Object, int, int)(0x7b4ea58020)
[ 2023-06-06T16:35:17.759     1000:  1801:  1801 V/LSPlant         ] lsplant.cc:492#void *lsplant::(anonymous namespace)::GenerateTrampolineFor(art::ArtMethod *): trampoline: count = 14, address = 7e949c6000, target = 7e949c6150
[ 2023-06-06T16:35:17.759     1000:  1801:  1801 V/LSPlant         ] lsplant.cc:518#bool lsplant::(anonymous namespace)::DoHook(lsplant::art::ArtMethod *, lsplant::art::ArtMethod *, lsplant::art::ArtMethod *): Generated trampoline 0x7e949c6150
[ 2023-06-06T16:35:17.759     1000:  1801:  1801 V/LSPlant         ] lsplant.cc:534#bool lsplant::(anonymous namespace)::DoHook(lsplant::art::ArtMethod *, lsplant::art::ArtMethod *, lsplant::art::ArtMethod *): Done hook: target(0x7b4f6fcbf8:0x1a200001) -> 0x7e949c6150; backup(0x7b4ea58020:0x1a200002) -> 0x79b15933d0; hook(0x7b4ea58040:0x12280009) -> 0x7bdb306260
[ 2023-06-06T16:35:17.759     1000:  1801:  1801 V/LSPosed         ] hook_bridge.cpp:57#lspd::Java_org_lsposed_lspd_nativebridge_HookBridge_hookMethod(JNIEnv *, jclass, jobject, jclass, jint, jobject)::finally::~finally(): New hook took 1137us
```

which corresponds to your code here: https://github.com/siavash79/AOSPMods/blob/87dc6bf6d880b8be05573282b0bb95839b861532/app/src/main/java/sh/siava/AOSPMods/modpacks/telecom/CallVibrator.java#L53


I am pretty sure this is an issue of LSPosed. So I will close this issue for now. If you do believe LSPosed is broken, you are welcomed to open a new issue with a minimum reproducible module (if applicable).

**Closed by yujincheng08** 2023-06-08 08:16 UTC
Labels: bug

**Comment by siavash79** [comment] 2023-06-28 06:40
As an update, apparently the problem arises randomly when package manager fails to load the APK file when it should. I was able to resolve it by full uninstall/reinstall of the APK. But at this point I'm not sure if it relates to package manager or LSposed

It might be worth noting that shortly after zygote, the apk is loaded correctly for other hooked packages

` Can not open /data/app/~~tqrwqsiEi0otj46osFwWQw==/sh.siava.AOSPMods-hPb05XNGV6CYQDdiFfPLJg==/base.apk
                 java.io.FileNotFoundException: /proc/1/root/data/app/~~tqrwqsiEi0otj46osFwWQw==/sh.siava.AOSPMods-hPb05XNGV6CYQDdiFfPLJg==/base.apk (No such file or directory)
                 	at java.util.zip.ZipFile.open(Native Method)
                 	at java.util.zip.ZipFile.<init>(ZipFile.java:293)
                 	at java.util.zip.ZipFile.<init>(ZipFile.java:252)
                 	at java.util.zip.ZipFile.<init>(ZipFile.java:198)
                 	at java.util.zip.ZipFile.<init>(ZipFile.java:212)
                 	at y0.g(Unknown Source:31)
                 	at T0.test(Unknown Source:57)
                 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:186)
                 	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
                 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
                 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:503)
                 	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
                 	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
                 	at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
                 	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
                 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:377)
                 	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:690)
                 	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
                 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:235)
                 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:519)
                 	at W0.s(Unknown Source:235)
                 	at s1.b(Unknown Source:24)
                 	at f1.onTransact(Unknown Source:197)
                 	at s1.onTransact(Unknown Source:12)
                 	at android.os.Binder.execTransactInternal(Binder.java:1339)
                 	at android.os.Binder.execTransact(Binder.java:1275)

failed to parse parse /data/app/~~tqrwqsiEi0otj46osFwWQw==/sh.siava.AOSPMods-hPb05XNGV6CYQDdiFfPLJg==/base.apk
                 android.content.pm.PackageParser$PackageParserException: Failed to parse /data/app/~~tqrwqsiEi0otj46osFwWQw==/sh.siava.AOSPMods-hPb05XNGV6CYQDdiFfPLJg==/base.apk
                 	at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1503)
                 	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1474)
                 	at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:980)
                 	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1189)
                 	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1103)
                 	at W0.s(Unknown Source:165)
                 	at s1.b(Unknown Source:24)
                 	at f1.onTransact(Unknown Source:169)
                 	at s1.onTransact(Unknown Source:12)
                 	at android.os.Binder.execTransactInternal(Binder.java:1339)
                 	at android.os.Binder.execTransact(Binder.java:1275)`
