### ISSUE TITLE
[BUG] Wi-Fi problems

### ISSUE THREAD

**Issue by denis1532** [LSPosed/LSPosed#380] opened 2021-03-20 00:44 UTC
**什么情况/What happened?**
After installing LSPosed, I face several problems:
• Wi-Fi stuck on "Receiving IP-address", only manual Wi-Fi reload helps
• Wi-Fi says "Connected, no access to the Internet", nothing helps

**Xposed模块列表/Xposed Module List**
All working great:
• LuckyPatcher
• CustoMIUIzer

**Magisk模块列表/Magisk Module List**
I guess all modules are working great
List:
• AdGuearn DNS
• App Systemizer
• Busybox for Android NDK
• HARDWARE OFF
• Riru 23.9
• Riru - LSPosed (1.2.2)
• Systemless Hosts
• Universal SafetyNet Fix

**版本信息/Versions**
• Android: Android 10 QKQ1.191215.002
• Magisk: 21.4
• Riru: 23.9
• LSPosed: 1.2.2
• Device: Redmi Note 9 Pro, xiaomi.eu 12.0.2.0 (MIUI), system in r/w

**相关日志/Related Logs**
[magisk_log_2021-03-20T03_26_29Z.log](https://github.com/LSPosed/LSPosed/files/6174613/magisk_log_2021-03-20T03_26_29Z.log)
[LSPosed_Modules_20210320_032724.log](https://github.com/LSPosed/LSPosed/files/6174618/LSPosed_Modules_20210320_032724.log)

**Comment by yujincheng08** [comment] 2021-03-20 00:53
plz try:
1. install latest canary magisk
2. upgrade riru to 25.2+
3. install latest CI build of LSPosed (grab from telegram channel)
3. disable all unrelated magisk modules and disable all xposed modules.

If the isuuse persists, install debug version of LSPosed and get FULL bootlog by adb logcat.

**Comment by yujincheng08** [comment] 2021-03-20 13:44
Someone said it's because of Riru. So we will close it until full bootlog is provided and confirmed as LSPosed's problem.

**Closed by yujincheng08** 2021-03-20 13:44 UTC
