### ISSUE TITLE
[Bug] Shortcut could not be created on OxygenOS 13 Stable official version

### ISSUE THREAD

**Issue by bai12123** [LSPosed/LSPosed#2235] opened 2022-11-18 17:12 UTC
### Steps to reproduce/复现步骤

Install LSPosed then reboot or create shortcuts manually

### Expected behaviour/预期行为

Shortcut should be added to home screen

### Actual behaviour/实际行为

Nothing happened.
This might not be the problem with my os because Sui's shortcut creating is working normally.
I'm using OxygenOS13 launcher (com.android.launcher)

### Xposed Module List/Xposed 模块列表

```shell
哔哩漫游 1.6.5
```

### Magisk Module List/Magisk 模块列表

```shell
Shaniko v0.6(126)
```

### LSPosed version/LSPosed 版本

6649

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25.2(25200)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-11-19T00_58_31.681111.zip](https://github.com/LSPosed/LSPosed/files/10043379/LSPosed_2022-11-19T00_58_31.681111.zip)

**Comment by bai12123** [comment] 2022-11-18 17:13
I saw other people posted about "cannot create shortcut"  #2142 #1872 , there are problems on coloros13, oos13, I don't know much about the code, so I want to ask, is this problem waiting for the new version to fix? Or do something else?

**Comment by yujincheng08** [comment] 2022-11-18 17:14
Duplicate of #1872

**Comment by yujincheng08** [comment] 2022-11-18 17:15
wont fix. this behavior violates CTS.

**Closed** 2022-11-18 17:14 UTC
Labels: bug

**Comment by bai12123** [comment] 2022-11-18 17:17
I read #1872 ， so I can only submit it to the rom devs to have them fix it?

**Comment by bai12123** [comment] 2022-11-18 17:20
It is estimated that it is not possible, thank you, I can only enter by dialing
