### ISSUE TITLE
[Bug] Cann't add shortcut

### ISSUE THREAD

**Issue by Marcocxy** [LSPosed/LSPosed#1994] opened 2022-06-15 07:29 UTC
### Steps to reproduce/复现步骤

Install LSPosed then reboot

### Expected behaviour/预期行为

Shortcut should be added to home screen.

### Actual behaviour/实际行为

Nothing happened.

### Xposed Module List/Xposed 模块列表

```shell
None yet.
```

### Magisk Module List/Magisk 模块列表

```shell
RescueBrick
uperf
zygisk_lsposed
zygisk_shamiko
zygisk-storage-isolation
```

### LSPosed version/LSPosed 版本

1.8.3-6574

### Android version/Android 版本

Coloros 12.1

### Magisk version/Magisk 版本

Magisk cae58c87-alpha

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

06-15 15:12:33.432   839  1279 E LSPosedService: add shortcut
06-15 15:12:33.432   839  1279 E LSPosedService: java.lang.SecurityException: Calling package name mismatch
06-15 15:12:33.432   839  1279 E LSPosedService: 	at com.android.server.pm.ShortcutService.verifyCaller(ShortcutService.java:1719)
06-15 15:12:33.432   839  1279 E LSPosedService: 	at com.android.server.pm.ShortcutService.verifyCaller(ShortcutService.java:1728)
06-15 15:12:33.432   839  1279 E LSPosedService: 	at com.android.server.pm.ShortcutService.getShortcuts(ShortcutService.java:2678)
06-15 15:12:33.432   839  1279 E LSPosedService: 	at android.content.pm.IShortcutService$Stub.onTransact(IShortcutService.java:690)
06-15 15:12:33.432   839  1279 E LSPosedService: 	at android.os.Binder.execTransactInternal(Binder.java:1221)
06-15 15:12:33.438   839  1279 E LSPosedService: add shortcut
06-15 15:12:33.438   839  1279 E LSPosedService: java.lang.SecurityException: Calling package name mismatch
06-15 15:12:33.438   839  1279 E LSPosedService: 	at com.android.server.pm.ShortcutService.verifyCaller(ShortcutService.java:1719)
06-15 15:12:33.438   839  1279 E LSPosedService: 	at com.android.server.pm.ShortcutService.verifyCaller(ShortcutService.java:1728)
06-15 15:12:33.438   839  1279 E LSPosedService: 	at com.android.server.pm.ShortcutService.getShortcuts(ShortcutService.java:2678)
06-15 15:12:33.438   839  1279 E LSPosedService: 	at android.content.pm.IShortcutService$Stub.onTransact(IShortcutService.java:690)
06-15 15:12:33.438   839  1279 E LSPosedService: 	at android.os.Binder.execTransactInternal(Binder.java:1221)

**Comment by vvb2060** [comment] 2022-06-15 07:30
Duplicate of #1872

**Closed by vvb2060** 2022-06-15 07:30 UTC
Labels: bug
