### ISSUE TITLE
[BUG] Manager app missing and module not loaded

### ISSUE THREAD

**Issue by ehahn** [LSPosed/LSPosed#808] opened 2021-07-10 22:40 UTC
**什么情况/What happened?**

After installing LSPosed and rebooting, the manager app is missing. If I extract it from the zip file and install it manually, it says that LSPosed is not installed.

**Xposed模块列表/Xposed Module List**

n/a

**Magisk模块列表/Magisk Module List**
- F-Droid Privileged Extension 2019-11-23
- MagiskHide Props Config v5.4.0-v129
- Universal SafetyNet Fix v1.1.1
(Disabling these two doesn't help)
- Riru and LSPosed

**版本信息/Versions**

Android: 9 (Moto G7 stock)

Magisk: 23.0 (23000)

Riru: 25.4.4.r426.05efc94

LSPosed: 1.4.7 (5803)

**相关日志/Related Logs**
- [magisk_install_log_2021-07-11T00:15:44Z.log](https://github.com/LSPosed/LSPosed/files/6796045/magisk_install_log_2021-07-11T00.15.44Z.log)
- [magisk_log_2021-07-11T00:33:32Z.log](https://github.com/LSPosed/LSPosed/files/6796046/magisk_log_2021-07-11T00.33.32Z.log)
- No LSPosed log because the module is not running

**Comment by etmatrix** [comment] 2021-07-11 07:57
try to catch boot log with logcat. 
Is better test with lsposed debug version

**Comment by ehahn** [comment] 2021-07-11 09:23
Logs:

[magisk_log_2021-07-11T11:05:34Z.log](https://github.com/LSPosed/LSPosed/files/6796614/magisk_log_2021-07-11T11.05.34Z.log)
[magisk_install_log_2021-07-11T10:45:56Z.log](https://github.com/LSPosed/LSPosed/files/6796615/magisk_install_log_2021-07-11T10.45.56Z.log)
[logcat_07-11-2021_11-12-06.txt](https://github.com/LSPosed/LSPosed/files/6796630/logcat_07-11-2021_11-12-06.txt)

Could be the same issue, however my logs don't mention Riru and EdXposed works.

**Comment by yujincheng08** [comment] 2021-07-11 09:31
This boot log is too late.

**Comment by yujincheng08** [comment] 2021-07-11 09:36
Use this module to catch full bootlog: https://t.me/hzrtools/10

**Comment by ehahn** [comment] 2021-07-11 09:56
[boot-2021-07-11-11-50-02.log](https://github.com/LSPosed/LSPosed/files/6796678/boot-2021-07-11-11-50-02.log)

**Comment by etmatrix** [comment] 2021-07-11 09:59
same [exception](https://github.com/LSPosed/LSPosed/issues/785#issuecomment-869187650) 
```
07-11 11:49:37.097  1317  1317 W rirud_java: Landroid/os/Build; failed initialization: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
07-11 11:49:37.097  1317  1317 W rirud_java:   at java.lang.String android.os.Build.getBuildNumber() (Build.java:1207)
07-11 11:49:37.097  1317  1317 W rirud_java:   at java.lang.String android.os.Build.deriveFingerprint() (Build.java:959)
07-11 11:49:37.097  1317  1317 W rirud_java:   at void android.os.Build.<clinit>() (Build.java:945)
07-11 11:49:37.097  1317  1317 W rirud_java:   at java.lang.String android.os.Build.access$000(java.lang.String) (Build.java:42)
07-11 11:49:37.097  1317  1317 W rirud_java:   at void android.os.Build$VERSION.<clinit>() (Build.java:201)
07-11 11:49:37.097  1317  1317 W rirud_java:   at java.lang.String com.android.internal.os.RuntimeInit.getDefaultUserAgent() (RuntimeInit.java:258)
07-11 11:49:37.097  1317  1317 W rirud_java:   at void com.android.internal.os.RuntimeInit.commonInit() (RuntimeInit.java:225)
07-11 11:49:37.097  1317  1317 W rirud_java:   at void com.android.internal.os.RuntimeInit.main(java.lang.String[]) (RuntimeInit.java:334)
07-11 11:49:37.097  1317  1317 W rirud_java: 
07-11 11:49:37.097  1317  1317 W rirud_java: Landroid/os/Build$VERSION; failed initialization: java.lang.ExceptionInInitializerError: 
07-11 11:49:37.097  1317  1317 W rirud_java:   at java.lang.String android.os.Build.access$000(java.lang.String) (Build.java:42)
07-11 11:49:37.097  1317  1317 W rirud_java:   at void android.os.Build$VERSION.<clinit>() (Build.java:201)
07-11 11:49:37.097  1317  1317 W rirud_java:   at java.lang.String com.android.internal.os.RuntimeInit.getDefaultUserAgent() (RuntimeInit.java:258)
07-11 11:49:37.098  1317  1317 W rirud_java:   at void com.android.internal.os.RuntimeInit.commonInit() (RuntimeInit.java:225)
07-11 11:49:37.098  1317  1317 W rirud_java:   at void com.android.internal.os.RuntimeInit.main(java.lang.String[]) (RuntimeInit.java:334)
07-11 11:49:37.098  1317  1317 W rirud_java: 
07-11 11:49:37.098  1317  1317 D AndroidRuntime: Shutting down VM
07-11 11:49:37.106  1317  1317 E AndroidRuntime: FATAL EXCEPTION: main
07-11 11:49:37.106  1317  1317 E AndroidRuntime: PID: 1317
07-11 11:49:37.106  1317  1317 E AndroidRuntime: java.lang.ExceptionInInitializerError
07-11 11:49:37.106  1317  1317 E AndroidRuntime:        at android.os.Build.access$000(Build.java:42)
07-11 11:49:37.106  1317  1317 E AndroidRuntime:        at android.os.Build$VERSION.<clinit>(Build.java:201)
07-11 11:49:37.106  1317  1317 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.getDefaultUserAgent(RuntimeInit.java:258)
07-11 11:49:37.106  1317  1317 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.commonInit(RuntimeInit.java:225)
07-11 11:49:37.106  1317  1317 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:334)
07-11 11:49:37.106  1317  1317 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
07-11 11:49:37.106  1317  1317 E AndroidRuntime:        at android.os.Build.getBuildNumber(Build.java:1207)
07-11 11:49:37.106  1317  1317 E AndroidRuntime:        at android.os.Build.deriveFingerprint(Build.java:959)
07-11 11:49:37.106  1317  1317 E AndroidRuntime:        at android.os.Build.<clinit>(Build.java:945)
07-11 11:49:37.106  1317  1317 E AndroidRuntime:        ... 5 more
07-11 11:49:37.110  1187  1359 I ServiceManager: Waiting for service 'package_native' on '/dev/binder'...
```

**Comment by ehahn** [comment] 2021-07-11 10:01
Also both my mr2013's phones are from Motorola.

**Comment by yujincheng08** [comment] 2021-07-11 10:04
Duplicate of #785

**Closed by yujincheng08** 2021-07-11 10:04 UTC
