### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by brandonsneiders** [LSPosed/LSPosed#1671] opened 2022-02-11 14:45 UTC
### Steps to reproduce/复现步骤

I installed xposed zygisk the latest version and flashed in magisk and then rebooted and it was not installed and yes, I have zygisk activated

### Expected behaviour/预期行为

I was waiting for it to install and I don't even get the application

### Actual behaviour/实际行为

It appears installed in magisk but the app does not come out and I already looked at the module directory and there is no ldps folder

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
log catcher and lsposed
```

### LSPosed version/LSPosed 版本

1.7.2 (6379)

### Android version/Android 版本

8.1.0

### Magisk version/Magisk 版本

24.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[boot-2022-02-11-09-20-10.log](https://github.com/LSPosed/LSPosed/files/8049421/boot-2022-02-11-09-20-10.log)

**Comment by vvb2060** [comment] 2022-02-11 14:56
```
02-11 09:19:52.744   948   948 W lspd    : Landroid/os/Build; failed initialization
02-11 09:19:52.744   948   948 W lspd    : Landroid/os/Build$VERSION; failed initialization
02-11 09:19:52.744   948   948 D AndroidRuntime: Shutting down VM
02-11 09:19:52.759   948   948 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
02-11 09:19:52.759   948   948 E AndroidRuntime: java.lang.ExceptionInInitializerError
02-11 09:19:52.759   948   948 E AndroidRuntime: 	at android.os.Build.-wrap2(Unknown Source:0)
02-11 09:19:52.759   948   948 E AndroidRuntime: 	at android.os.Build$VERSION.<clinit>(Build.java:194)
02-11 09:19:52.759   948   948 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.getDefaultUserAgent(RuntimeInit.java:203)
02-11 09:19:52.759   948   948 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.commonInit(RuntimeInit.java:170)
02-11 09:19:52.759   948   948 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:279)
02-11 09:19:52.759   948   948 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
02-11 09:19:52.759   948   948 E AndroidRuntime: 	at android.os.Build.getBuildNumber(Build.java:1145)
02-11 09:19:52.759   948   948 E AndroidRuntime: 	at android.os.Build.deriveFingerprint(Build.java:826)
02-11 09:19:52.759   948   948 E AndroidRuntime: 	at android.os.Build.<clinit>(Build.java:812)
02-11 09:19:52.759   948   948 E AndroidRuntime: 	... 5 more
02-11 09:19:52.774   948   948 E AndroidRuntime: Error reporting crash
02-11 09:19:52.774   948   948 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.handleApplicationCrash(android.os.IBinder, android.app.ApplicationErrorReport$ParcelableCrashInfo)' on a null object reference
02-11 09:19:52.774   948   948 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:116)
02-11 09:19:52.774   948   948 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-11 09:19:52.774   948   948 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
02-11 09:19:52.774   948   948 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
02-11 09:19:52.774   948   948 I Process : Sending signal. PID: 948 SIG: 9
```
Duplicate of #785

**Closed by vvb2060** 2022-02-11 14:56 UTC
Labels: bug

**Comment by brandonsneiders** [comment] 2022-02-11 14:59
> ```
> 02-11 09:19:52.744   948   948 W lspd    : Landroid/os/Build; failed initialization
> 02-11 09:19:52.744   948   948 W lspd    : Landroid/os/Build$VERSION; failed initialization
> 02-11 09:19:52.744   948   948 D AndroidRuntime: Shutting down VM
> 02-11 09:19:52.759   948   948 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
> 02-11 09:19:52.759   948   948 E AndroidRuntime: java.lang.ExceptionInInitializerError
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at android.os.Build.-wrap2(Unknown Source:0)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at android.os.Build$VERSION.<clinit>(Build.java:194)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.getDefaultUserAgent(RuntimeInit.java:203)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.commonInit(RuntimeInit.java:170)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:279)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at android.os.Build.getBuildNumber(Build.java:1145)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at android.os.Build.deriveFingerprint(Build.java:826)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at android.os.Build.<clinit>(Build.java:812)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	... 5 more
> 02-11 09:19:52.774   948   948 E AndroidRuntime: Error reporting crash
> 02-11 09:19:52.774   948   948 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.handleApplicationCrash(android.os.IBinder, android.app.ApplicationErrorReport$ParcelableCrashInfo)' on a null object reference
> 02-11 09:19:52.774   948   948 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:116)
> 02-11 09:19:52.774   948   948 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
> 02-11 09:19:52.774   948   948 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
> 02-11 09:19:52.774   948   948 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
> 02-11 09:19:52.774   948   948 I Process : Sending signal. PID: 948 SIG: 9
> ```
> 
> Duplicate of #785

how do i solve my problem :c

**Comment by brandonsneiders** [comment] 2022-02-11 14:59
> ```
> 02-11 09:19:52.744   948   948 W lspd    : Landroid/os/Build; failed initialization
> 02-11 09:19:52.744   948   948 W lspd    : Landroid/os/Build$VERSION; failed initialization
> 02-11 09:19:52.744   948   948 D AndroidRuntime: Shutting down VM
> 02-11 09:19:52.759   948   948 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
> 02-11 09:19:52.759   948   948 E AndroidRuntime: java.lang.ExceptionInInitializerError
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at android.os.Build.-wrap2(Unknown Source:0)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at android.os.Build$VERSION.<clinit>(Build.java:194)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.getDefaultUserAgent(RuntimeInit.java:203)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.commonInit(RuntimeInit.java:170)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:279)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at android.os.Build.getBuildNumber(Build.java:1145)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at android.os.Build.deriveFingerprint(Build.java:826)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	at android.os.Build.<clinit>(Build.java:812)
> 02-11 09:19:52.759   948   948 E AndroidRuntime: 	... 5 more
> 02-11 09:19:52.774   948   948 E AndroidRuntime: Error reporting crash
> 02-11 09:19:52.774   948   948 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.handleApplicationCrash(android.os.IBinder, android.app.ApplicationErrorReport$ParcelableCrashInfo)' on a null object reference
> 02-11 09:19:52.774   948   948 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:116)
> 02-11 09:19:52.774   948   948 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
> 02-11 09:19:52.774   948   948 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
> 02-11 09:19:52.774   948   948 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
> 02-11 09:19:52.774   948   948 I Process : Sending signal. PID: 948 SIG: 9
> ```
> 
> Duplicate of #785

how do i solve my problem :c

**Comment by canyie** [comment] 2022-02-11 15:03
> how do i solve my problem :c

Use another rom instead.

**Comment by yujincheng08** [comment] 2022-02-11 15:10
Duplicate of #785

**Comment by yujincheng08** [comment] 2022-02-11 15:12
> how do i solve my problem :c

Manually set your fingerprint just after post-fs-data
