### ISSUE TITLE
[Bug] Crashes after first run

### ISSUE THREAD

**Issue by LenaTDDS** [LSPosed/LSPosed#1967] opened 2022-05-29 07:42 UTC
### Steps to reproduce/复现步骤

1. Boot your device
2. Run LSPosed
3. Close LSPosed
4. Try to run it again

### Expected behaviour/预期行为

Everything work fine

### Actual behaviour/实际行为

Application shell crashes

### Xposed Module List/Xposed 模块列表

```shell
https://github.com/neoblackxt/AnyWebView - enabled
LP (Lucky Patcher) - disabled
```

### Magisk Module List/Magisk 模块列表

```shell
Dialer Framework for Google Phone
Minimal microG Pack NoGoolag Edition
Shamiko
Universal SafetyNet Fix
vshaped notch
Zygisk LSPosed
```

### LSPosed version/LSPosed 版本

1.8.3

### Android version/Android 版本

12

### Magisk version/Magisk 版本

24 (canary)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

https://www.toptal.com/developers/hastebin/yuxezevale

**Comment by yujincheng08** [comment] 2022-05-29 07:44
Duplicate of #1919

**Closed by yujincheng08** 2022-05-29 07:44 UTC
Labels: bug

**Comment by LeeBinder** [comment] 2023-07-05 17:59
see [here](https://github.com/orgs/LSPosed/discussions/2602) for a possible work-around - it solved this issue for me.
