### ISSUE TITLE
[BUG] Lsposed Manager sometimes crash

### ISSUE THREAD

**Issue by txyyh** [LSPosed/LSPosed#751] opened 2021-06-18 08:21 UTC
**什么情况/What happened?**
Lsposed Manager sometimes crash when I switch interface.

**Xposed模块列表/Xposed Module List**

I have used sm.ms, if these pictures disappeared, please let me know.
![Xposed Modules](https://sm.ms/image/Hp25Zrj8PWIwLtS)

**Magisk模块列表/Magisk Module List**
![Magisk Modules](https://sm.ms/image/AyHqUSDhaOItjL3)

**版本信息/Versions**

Android:Mokee 90.0
version number: mk_hltetmo-userdebug 9 PQ3A.190801.002 eng.buildb.20210613.103651 dev-keys

Magisk:23.0 (23000)
with Ramdisk enabled, A/B disabled, SAR disabled.
Magisk Hide was enabled, and I added the app "网易云音乐".

Riru:v25.4.4.r426.05efc94

LSPosed:v1.4.5 (5767)

**相关日志/Related Logs**

Here are 3 logs of Lsposed Manager, if you want Lsposed module logs, please leave a comment below.
PS: I have not reboot device between these crashes.

Build version: v1.4.5 (5767) 
Current date: 2021-06-18 15:19:44 
Device: Samsung SM-N900V 
 
SDK: 28 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.WindowInsets.getSystemWindowInsetBottom()' on a null object reference
	at x1.run(:1)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Build version: v1.4.5 (5767) 
Current date: 2021-06-18 15:22:39 
Device: Samsung SM-N900V 
 
SDK: 28 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.WindowInsets.getSystemWindowInsetBottom()' on a null object reference
	at x1.run(:1)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Build version: v1.4.5 (5767) 
Current date: 2021-06-18 15:24:26 
Device: Samsung SM-N900V 
 
SDK: 28 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.WindowInsets.getSystemWindowInsetBottom()' on a null object reference
	at x1.run(:1)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by yujincheng08** [comment] 2021-06-18 08:32
How to reproduce it?

**Comment by txyyh** [comment] 2021-06-18 08:47
@yujincheng08 I can't find it.
Only when I switch interface will it crash **sometimes**.

**Comment by txyyh** [comment] 2021-06-18 08:56
I might know why.
This bug have not reproduced after system reboot, and I just enabled system framework to some apps before reboot.
Hopeful it can help you.

**Comment by yujincheng08** [comment] 2021-07-07 16:10
Closed as it cannot reproduce.

**Closed by yujincheng08** 2021-07-07 16:10 UTC
