### ISSUE TITLE
[Bug] Missing translation RU

### ISSUE THREAD

**Issue by Alexey71** [LSPosed/LSPosed#1105] opened 2021-09-12 11:44 UTC
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Add missing russian translation:
Dark theme
Always on
Always off
Follow system

### Describe the solution you'd like/描述你想要的解决方案

Already added here https://github.com/RikkaApps/RikkaX/blob/master/core/core/src/main/res/values-ru/strings.xml

I try latest LSPosed manager https://github.com/LSPosed/LSPosed/actions/runs/1226389266
No found translation

**Comment by vvb2060** [comment] 2021-09-12 11:46
wait

**Comment by yujincheng08** [comment] 2021-09-12 11:46
Duplicate of #302

**Closed** 2021-09-12 11:46 UTC
Labels: enhancement

**Comment by Alexey71** [comment] 2021-09-12 11:48
Need wait Releases?

**Comment by yujincheng08** [comment] 2021-09-12 11:49
wait upstream (rikkax) release
