### ISSUE TITLE
[Bug] 点击桌面上的LSPosed，app打不开

### ISSUE THREAD

**Issue by xmhwws** [LSPosed/LSPosed#2259] opened 2022-12-02 11:31 UTC
### Steps to reproduce/复现步骤

点击桌面上的LSPosed，app打不开

### Expected behaviour/预期行为

app正常运行

### Actual behaviour/实际行为

lsposed闪退
我记得好像是安装lsposed后，第一次可以正常启动，后面就一直打不开了
我改了aosp源码里面的su，magisk也改了，通过命令行执行su无法获取root权限，会不会是这个原因？

![image](https://user-images.githubusercontent.com/42903751/205282698-839916f3-9ffa-4f21-94e8-ad0dce5a0b40.png)

### Xposed Module List/Xposed 模块列表

```shell
打不开lsposed，所以不清楚，但是记得插件很少
```

### Magisk Module List/Magisk 模块列表

```shell
Move Certificates v1.9
Shamiko v0.6（126）
Zygisk-LSPosed v1.8.4（6609）
```

### LSPosed version/LSPosed 版本

1.8.4（6609）

### Android version/Android 版本

10

### Magisk version/Magisk 版本

25203（自编译版本，改了su命令行和.magisk）

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

2022-12-02 19:15:48.693 13419-13419 AndroidRuntime          com.android.shell                    D  Shutting down VM
2022-12-02 19:15:48.693 13419-13419 AndroidRuntime          com.android.shell                    E  FATAL EXCEPTION: main
                                                                                                    Process: com.android.shell, PID: 13419
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7356)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
                                                                                                    	at com.android.shell.BugreportWarningActivity.onCreate(BugreportWarningActivity.java:54)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7825)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7814)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:214) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7356) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2022-12-02 19:15:48.695  5085-15553 ActivityTaskManager     system_process                       W    Force finishing activity com.android.shell/.BugreportWarningActivity

**Comment by yujincheng08** [comment] 2022-12-02 11:32
Duplicate of #1919

**Closed by yujincheng08** 2022-12-02 11:32 UTC
Labels: bug

**Comment by xmhwws** [comment] 2022-12-02 11:41
@yujincheng08 我看了#1919 ，似乎解释为ROM问题？
但我是基于aosp源码编译的系统，只是在源码上加了一些定制，理论上不会干扰lsposed运行
可能不是ROM问题

手机：pixel 4 xl
aosp版本：android-10.0.0_r41
build ID：QQ3A.200805.001

<img width="634" alt="clipboard" src="https://user-images.githubusercontent.com/42903751/205284579-7f28a38c-07fe-42f0-bb3c-8dcef27d411a.png">

**Comment by revercc** [comment] 2023-01-06 17:42
@yujincheng08 @xmhwws 我自编译的android_10.0.0_r7在pixel4上出现了相同的错误，使用Magisk25200 + Zygisk-LSPosed v1.8.4（6609）, 新编译的系统并且稳定出现这个问题。

**Comment by revercc** [comment] 2023-01-06 17:50
> 

我什么都没有改变，只是单纯的编译源码并进行magisk root
