### ISSUE TITLE
[BUG]IllegalStateException

### ISSUE THREAD

**Issue by inkhog** [LSPosed/LSPosed#170] opened 2021-02-23 00:07 UTC
the LSPosed Manager app infinitely crashed with the same log.
```
Build version: v0.5.4.1 (5250) 
Current date: 2021-02-23 08:00:51 
Device: Xiaomi M2002J9E 
 
SDK: 29 
 
Stack trace:  
c.e.b.v: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at c.e.b.i.b(:13)
	at d.a.a.a.d.d$a.d(:5)
	at i.n0.g.e$a.run(:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
	at c.e.b.c0.a.o(:6)
	at c.e.b.a0.z.a.a(:4)
	at c.e.b.i.b(:8)
	... 5 more
```

I tried disabling the magisk module and rebooting my device and reinstalling the app, it didn't work, either.

**Comment by Proanx** [comment] 2021-02-23 00:42
给它断网就行了

**Comment by yujincheng08** [comment] 2021-02-23 00:48
Duplicate of #169

**Closed by yujincheng08** 2021-02-23 00:48 UTC
